### PR TITLE
Sensor module v1

### PR DESCRIPTION
**Pull request by tyler-alway**
Sensor module and the i2c flight mode library MVP

### CODE REVIEW

**Comment by cwalexand** [comment]
How was this tested? What were the results?
Test mode doesn't build. Should it?

---

sensor.rs:
The sensor module should not contain references to the embedded libraries (lines 16-17):
use self::i2cdev::core::_;
use self::i2cdev::linux::_;

The read_reg function is only called once from line 61 -- perhaps the 2 lines in the function should be moved here and the function deleted?

Convert tabs to spaces on lines 29-32, 36-37, 71.

---

i2c.rs:
The init function should not return a LinuxI2CDevice -- The LinuxI2CDevice should be specific to flight mode.

The read_reg function is only called once from line 18 -- perhaps the 2 lines in the function should be moved here and the function deleted?

Convert tabs to spaces on lines 18-21.

rustdoc comments would be nice.

---

Cargo.toml (test mode):
i2cdev = "*" should not be in test mode.

---

It would be nice to not have build warnings:
../common/sensor.rs:22:1: 24:2 warning: type `Sensor_Module` should have a camel case name such as `SensorModule`, #[warn(non_camel_case_types)] on by default
../common/sensor.rs:22 pub struct Sensor_Module {
../common/sensor.rs:23     pub i2c: LinuxI2CDevice,
../common/sensor.rs:24 }

**Comment by tyler-alway** [comment]
-As for testing I have been running it on the A20 board I'm not quite sure what the gyro outputs should be because Jamey and I have yet to figure out why the python code is dividing the sensor data for the gyro by 114.3 where the documentation for the MPU-6050 and MPU-9150 states that for the gyro mode of +or - 250dps the number should be 131. Thought the code does connect up to the correct device and can read data. 
- Test mode should now compile but do nothing. 
- Moved any reference to the LinuxI2CDevice to the flight mode libs. This may mess with what Chris was working on but I realized that the testing I had done with compiling test mode was on Linux only and wouldn't work on windows. 
- Removed the read_reg function. 
- Added blank function so that test mode will compile but wont do anything. 
- As for the tabs would you like to to remove all tabs from the code and replace them with spaces because all indentation was done with tabs and I have no problem fixing it. 
- In i2c init no longer returns a LinuxI2CDevice just a Myi2c also removed the read_reg function. 
- Cargo.toml (test mode):
  removed: i2cdev = "*" should not be in test mode.
- Fixed the warnings that related to the sensor module

I think that is everything please tell me if I missed something or if you see anything else. Thanks for your feedback.

**Comment by tyler-alway** [comment]
Also I get the same readings that Jameys program does.

**Comment by chrisliebert** [comment]
I'll merge it with test mode once it compiles. Currently there is ambiguity with SensorModule and Sensor_Module and it won't compile. I tried replacing Sensor_Module with SensorModule and it compiled but crashed when initializing the sensor (this is expected though because I have no I2C device on my machine).

**Comment by cwalexand** [comment]
Looks like main.rs still needs an update:

../common/main.rs:3:5: 3:26 error: unresolved import `sensor::Sensor_Module`. There is no `Sensor_Module` in `sensor`. Did you mean to use `SensorModule`? [E0432]
../common/main.rs:3 use sensor::Sensor_Module;

---

The design for flight mode i2c should probably be updated.

---

Tabs are generally bad in source code because they can vary in width depending on your settings. So, things may look fine in one environment, but bad in another. Unfortunately, we don't have a coding standard on this project, but all that I have used say don't use tabs. There's a trick you can do in vim:

:syntax on
:set syntax=whitespace

Then, tabs are green and spaces are red. There are still some tab problems in sensor.rs and i2c.rs, but you can decide if it's worth fixing.

---

Otherwise, looks good to me.

**Comment by tyler-alway** [comment]
Fixed main, updated design, and changed all tab to spaces.

**Comment by tyler-alway** [comment]
sensor_module_v1 is now up to date with master and compiles in test and flight mode.

**Comment by chrisliebert** [comment]
I did not intend to make the commits "merged sensor_module_v1" and "Merge branch 'sensor_module_v1' of https://github.com/hgb2/PSAS-Capstone". Git did that for me when I was trying to switch branches.

**Comment by tyler-alway** [comment]
Its ok I have had some strange stuff happen with git too. Also it seems that it still works so I'm not sure if the changes affected my parts at all. And if they did I'm not really sure how to undo things on git hub.

**Pull request merged**
