### PR TITLE
Revert "Testmode"

### PR DESCRIPTION
**Pull request by chrisliebert**
Reverts hgb2/PSAS-Capstone#23

---

This change is [Reviewable](https://reviewable.io/reviews/hgb2/psas-capstone/24)

### CODE REVIEW

**Comment by cwalexand** [comment]
I vote no. Why are you doing this?

**Comment by BrianBreniser** [comment]
I second that, why is this being reverted?

**Comment by BrianBreniser** [comment]
I'm still unsure of why this pull request exists. Chris can you help us understand?

**Comment by BrianBreniser** [comment]
With no extra information on why we are doing this, I'm not going to merge these changes.

**Pull request closed without merging**
