### PR TITLE
Added Main Logic

### PR DESCRIPTION
**Pull request by hgb2**
Ported to new base folder structure and changed the expected arguments to the init functions to match new design changes.

### CODE REVIEW

**Comment by pclee777** [comment]
As mentioned on Slack, data formatter doesn't need a init function - looks good otherwise.

**Comment by cwalexand** [comment]
control.rs:
Put the call to gpio::init() back in to support the library developers.

sensor.rs:
Put the call to i2c::init() back in to support the library developers.

main.rs:
How do we exit the loop? Using ^C may leave gpio pins in an exported state ... not sure if that's a real issue or not.

A potential unit test could verify that the loop executes at the expected rate.

I see that it is going to change, but a control loop rate of 120 Hz seems too fast. We should probably find out from the control guys what the rocket requires rather than letting JSBSim drive the decision. In the meantime, could we turn this down to 10 Hz or so?

The design says that an emergency control exception should be thrown, but it's not in the code. Add it or update the design to not do that.

Main should initialize a UDP socket and pass it to the data formatter.

**Comment by cwalexand** [comment]
Looks good to me. Although, I'd like to see a unit test that shows that the loop executes at 10 Hz now. But, this isn't something we would want running during normal operation. Could we use rust's debug macros to turn on/off code instrumentation that checks loop frequency? Anyway, it seems like a useful test to me, but I'm okay if you want to skip or postpone it.

A couple notes to wrap up my previous comments:
1. Decided to continue using ^C to exit the loop. If it proves to be a problem, we'll fix it later.
2. We should create something that reminds us to determine what the control loop frequency should really be -- git issue?  trello something?

**Comment by BrianBreniser** [comment]
Sorry for the late reply, I wanted to check this out much sooner than I was able too. In pseudocode it's hard to represent this, during my design feedback I mentioned this, but here I need to make the understanding solid. In order to take advantage of error handling in rust, and subsequently reduce bugs, and crashes (during flight!), we need to use the Option() or Result() abstractions in Rust.

If a function does not need to return anything, just an Ok() or Err() will do
`fn okay_or_not() -> Result((), ()) {
    if test == true {
        Ok(())
    }
    if test == false {
        Err(())
    }
}`

You can also use `Result(i32, i32)`, so that `Ok(100)` means it's good and returned 100 and `Err(1)` gives an error value of 1.

You could also use the Option() type, if you don't need error values, such as

`fn has_something_or_not() -> Option(i32) {if test == true { Option(100) } if test == false {None}}`

As well, you could also use `Option( () )` (notice the empty parenthesis in the option type, that is an empty object), this allows the calling function to know if there was an error, but without having to return any integers that might not be caught.

I'm in favor of the `Ok()`, `Err()` syntax, since we can return error codes that way

Edited: I messed up some Rust syntax, and fixed it.

**Pull request merged**
