### PR TITLE
Main iteration 1

### PR DESCRIPTION
**Pull request by hgb2**
I added main's logic. Looking for feedback about tests (I don't know what tests main should have). I removed the contents of lib.rs because it caused the modules other than main to be compiled first (I think) and report that the SharedMemory structure in main.rs does not exist. Does anyone know what the best fix for that would be?

### CODE REVIEW

**Comment by BrianBreniser** [comment]
Main should be controlling control_module, not control_interface, according to our design, swap the interfaces with module files, and that should be good.

**Comment by BrianBreniser** [comment]
lib.rs should be the conductor of shared library code, you can put the data structure in a separate file, and call it in other library files I believe. If you try/tried it and it doesn't work, I suppose it's not the end of the world that lib.rs is removed, however, it is more idiomatic rust to use it, and it will make the code more expandable, so please give that a solid shot please.

**Comment by BrianBreniser** [comment]
Thanks for adding dummy functions in other files so it could compile :+1:

**Comment by pclee777** [comment]
If we are going by Cort's suggestion in the email between Cort, Harrison, Tyler and myself, shared memory should be excluded from the init functions since shared memory is going to be passed to the update functions in the Control, Sensor, and Data Formatter modules - this is due to Rust's ownership/borrowing system.

**Comment by BrianBreniser** [comment]
#### Please make changes against the new master branch, as the prototype code branch was merged recently

Sorry about the rework Harrison, it's my fault for creating a base repository that didn't meet our requirements. If you could port your changes to the current master branch, including previous comments on your current code, and resubmit, that would be wonderfull. As for how to test main, it's very possible we don't need unit tests for main, and will rely on integration tests, considering the context of what main does, let's see what the new pull request has, and I'll have more detail then.

**Pull request closed without merging**
