### PR TITLE
Simulation

### PR DESCRIPTION
**Pull request by chrisliebert**
Initialized the i2c device with a pointer to MyPIns in test mode (no-op in flight mode)

---

This change is [Reviewable](https://reviewable.io/reviews/hgb2/psas-capstone/20)

### CODE REVIEW

**Comment by chrisliebert** [comment]
Looks like I had rustfmt enabled on save which is why the whitespace got changed. The actual change is minimal.

**Comment by chrisliebert** [comment]
Please do not merge this pull request, it has interspersed formatting changes and will be used for reference only.

**Comment by cwalexand** [comment]
I disagree with all of the changes proposed for common files -- control.rs, main.rs, and sensor.rs.

I also disagree with the changes proposed for flight_mode/src/i2c.rs -- the i2c should not be using gpio pins.

Please close this pull request since it won't be merged anyway.

**Comment by chrisliebert** [comment]
The I2C device does not use the GPIO pins in flight mode, but since we have a common main interface I believe it is necessary in order to access the pins in test mode. In test mode, the concept of a sensor involves the simulation device which requires both GPIO and I2C components. @cwalexand can you offer an alternate solution?

**Pull request closed without merging**
